spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practicedb1?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      
server:
  tomcat:
    threads:
      max: 200
